version: '3'

services:
  nginx:
    image: matiux/debian-nginx:symfony
    # build:
    #   context: ./docker/nginx
    #   args:
    #     - FRAMEWORK=${FRAMEWORK}
    ports:
      - '8080:80'
    depends_on:
      - php
    volumes:
      - ./docker/logs/nginx/:/var/log/nginx
      - ./:/var/www/app
  php:
    #build: ./docker/php/7.1-fpm
    image: matiux/php:7.1-fpm
    tty: true # -t option in docker
    stdin_open: true # -i option in docker
    volumes:
      - ./:/var/www/app
    environment:
      - APP_ENV=${APP_ENV}
  mariadb:
    image: mariadb
    restart: always
    volumes:
      - ./docker/data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_ROOT_PASSWORD}
      # - MARIADB_DATABASE=app_db
      # - MARIADB_USER=app_db_user
      # - MARIADB_PASSWORD=
    ports:
      - '3307:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    environment:
      - PMA_HOST=mariadb
  # memcached:
  #   image: memcached:latest
  #   volumes:
  #     - ./docker/data/memcached:/var/lib/memcached
  # redis_db:
  #   image: redis:alpine
  #   #command: redis-server --requirepass redis
  #   ports: ["6379"]
