version: '3'

services:
  nginx:
    container_name: nginx.1
    build: ./docker/nginx
    ports:
      - '8080:80'
    depends_on:
      - php
    volumes:
      - ./docker/logs/nginx/:/var/log/nginx
      - ./:/var/www/app
  php:
    build: ./docker/php/7.1-fpm
    volumes:
      - ./:/var/www/app
      # - ./nginx/html:/var/www/html
      #- ./php7-fpm/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    environment:
      - APP_ENV=${APP_ENV}
      #- XDEBUG_HOST: ${XDEBUG_HOST}
    #command: sh ./docker/custom_task/fix_sf_permissions.sh
  mariadb:
    build: ./docker/mariadb
    volumes:
      - ./docker/data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD="${DOCKER_MYSQL_ROOT_PASSWORD}"
       # - MARIADB_DATABASE=app_db
       # - MARIADB_USER=app_db_user
       # - MARIADB_PASSWORD=
#    ports:
#      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    environment:
      - PMA_HOST=mariadb
    # memcached:
    #   build: ./docker/cache/memcached
    #   volumes:
    #     - ./docker/data/memcached:/var/lib/memcached
  redis_db:
    build: ./docker/cache/redis
    #command: redis-server --requirepass redis
    container_name: redis
    ports: ["6379"]
